# -*- coding: utf-8 -*-
"""Demographic Data Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkIZnJhdtgXOaWDQlW__Redjb4iYqV86
"""

import pandas as pd

def calculate_demographic_data(print_data=True):
    # Read data from CSV file
    df = pd.read_csv("adult.data.csv")

    # 1. Count the number of people for each race
    race_count = df['race'].value_counts()

    # 2. Calculate the average age of men
    average_age_men = round(df[df['sex'] == 'Male']['age'].mean(), 1)

    # 3. Calculate the percentage of people with a Bachelor's degree
    percentage_bachelors = round((df['education'].value_counts(normalize=True)['Bachelors'] * 100), 1)

    # 4. Split data into higher education (Bachelors, Masters, Doctorate) and lower education
    higher_education = df[df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])]
    lower_education = df[~df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])]

    # 5. Percentage of people with higher education earning >50K
    higher_education_rich = round((higher_education[higher_education['salary'] == '>50K'].shape[0] / higher_education.shape[0]) * 100, 1)

    # 6. Percentage of people without higher education earning >50K
    lower_education_rich = round((lower_education[lower_education['salary'] == '>50K'].shape[0] / lower_education.shape[0]) * 100, 1)

    # 7. Minimum number of hours worked per week
    min_work_hours = df['hours-per-week'].min()

    # 8. Percentage of people working minimum hours per week earning >50K
    num_min_workers = df[df['hours-per-week'] == min_work_hours]
    rich_percentage = round((num_min_workers[num_min_workers['salary'] == '>50K'].shape[0] / num_min_workers.shape[0]) * 100, 1)

    # 9. Calculate percentage of >50K earners by country
    country_salary = df.groupby('native-country')['salary'].value_counts(normalize=True).unstack()
    # Find country with highest percentage of >50K earners
    highest_earning_country = (country_salary['>50K'] * 100).idxmax()
    highest_earning_country_percentage = round((country_salary['>50K'] * 100).max(), 1)

    # 10. Most popular occupation for >50K earners in India
    top_IN_occupation = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]['occupation'].value_counts().idxmax()

    # Print results if print_data = True
    if print_data:
        print("Number of each race:\n", race_count)
        print("Average age of men:", average_age_men)
        print(f"Percentage with Bachelors degrees: {percentage_bachelors}%")
        print(f"Percentage with higher education that earn >50K: {higher_education_rich}%")
        print(f"Percentage without higher education that earn >50K: {lower_education_rich}%")
        print("Min work time:", min_work_hours, "hours/week")
        print(f"Percentage of rich among those who work fewest hours: {rich_percentage}%")
        print("Country with highest percentage of rich:", highest_earning_country)
        print("Highest percentage of rich people in country:", highest_earning_country_percentage)
        print("Top occupation in India for >50K earners:", top_IN_occupation)

    # Return results as dictionary
    return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage': highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation
    }