# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUyq_VzpRTMhs1B5JUyiYgKInG8u2CEg
"""

# main.py

from demographic_data_analyzer import calculate_demographic_data
import unittest
import test_module

def run_analyzer():
    """
    Run the demographic data analyzer and print results.
    """
    print("Running Demographic Data Analyzer...\n")
    calculate_demographic_data(print_data=True)

def run_tests():
    """
    Run unit tests from test_module.py
    """
    print("\nRunning Unit Tests...\n")
    unittest.TextTestRunner().run(unittest.TestLoader().loadTestsFromModule(test_module))

if __name__ == "__main__":
    # First run the analyzer to see the results
    run_analyzer()

    # Then run the tests to validate correctness
    run_tests()