# -*- coding: utf-8 -*-
"""test_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsHZU2dyJmGZY73EDtCNfSJqwSr_nx_0
"""

# test_module.py

import unittest
import pandas as pd
from demographic_data_analyzer import calculate_demographic_data

class DemographicAnalyzerTest(unittest.TestCase):

    def setUp(self):
        # Run the analyzer once and store results for testing
        self.results = calculate_demographic_data(print_data=False)

    def test_race_count(self):
        # Check that race_count is a Pandas Series and not empty
        self.assertIsInstance(self.results['race_count'], pd.Series)
        self.assertGreater(len(self.results['race_count']), 0)

    def test_average_age_men(self):
        # Average age of men should be a float
        self.assertIsInstance(self.results['average_age_men'], float)

    def test_percentage_bachelors(self):
        # Percentage of bachelors should be between 0 and 100
        self.assertGreaterEqual(self.results['percentage_bachelors'], 0)
        self.assertLessEqual(self.results['percentage_bachelors'], 100)

    def test_higher_education_rich(self):
        # Higher education rich percentage should be between 0 and 100
        self.assertGreaterEqual(self.results['higher_education_rich'], 0)
        self.assertLessEqual(self.results['higher_education_rich'], 100)

    def test_lower_education_rich(self):
        # Lower education rich percentage should be between 0 and 100
        self.assertGreaterEqual(self.results['lower_education_rich'], 0)
        self.assertLessEqual(self.results['lower_education_rich'], 100)

    def test_min_work_hours(self):
        # Minimum work hours should be an integer and positive
        self.assertIsInstance(self.results['min_work_hours'], int)
        self.assertGreater(self.results['min_work_hours'], 0)

    def test_rich_percentage(self):
        # Rich percentage among min workers should be between 0 and 100
        self.assertGreaterEqual(self.results['rich_percentage'], 0)
        self.assertLessEqual(self.results['rich_percentage'], 100)

    def test_highest_earning_country(self):
        # Highest earning country should be a string
        self.assertIsInstance(self.results['highest_earning_country'], str)

    def test_highest_earning_country_percentage(self):
        # Percentage should be between 0 and 100
        self.assertGreaterEqual(self.results['highest_earning_country_percentage'], 0)
        self.assertLessEqual(self.results['highest_earning_country_percentage'], 100)

    def test_top_IN_occupation(self):
        # Top occupation in India should be a string
        self.assertIsInstance(self.results['top_IN_occupation'], str)

if __name__ == "__main__":
    unittest.main()